### ISSUE TITLE
关于mixin.less中的clear-float函数

### ISSUE THREAD

**Issue by chestnutchen** [ecomfe/esui#388]
https://github.com/ecomfe/esui/blob/master/src/css/mixin.less#L10

```less
    // 清除浮动
    .clear-float () {
        display: block;
        &:after {
            content: ".";
            display: block;
            height: 0;
            clear: both;
            visibility: hidden;
        }
    }
 ```

content的值'.'是不是应该去掉，chrome39似乎出了个bug（很难描述，不过能100%复现在Region控件中），这个清除浮动的content会触发。
